# Generated by Django 3.0.6 on 2021-02-05 22:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(max_length=50)),
                ('parent_last_name', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=50)),
                ('parent_email', models.CharField(max_length=50)),
                ('child_first_name', models.CharField(max_length=50)),
                ('child_last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('event_id', models.CharField(max_length=50)),
                ('date_registered', models.DateField()),
            ],
        ),
    ]
