# Generated by Django 3.0.6 on 2021-02-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='event_id',
            new_name='event_occurrence_id',
        ),
    ]
