# Generated by Django 3.0.6 on 2021-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialreg', '0002_auto_20210206_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_registered',
            field=models.DateTimeField(),
        ),
    ]
